[transport-udp]
type=transport
protocol=udp
bind=0.0.0.0:5060

[31]
type=endpoint
context=ramais_internos
disallow=all
allow=ulaw, alaw
auth=auth31
aors=31

[auth31]
type=auth
auth_type=userpass
password=pswd1         ; <-- choisir le mot d epasse
username=31

[31]
type=aor
max_contacts=1

[32]
type=endpoint
context=ramais_internos
disallow=all
allow=ulaw
allow=alaw
auth=auth32
aors=32

[auth32]
type=auth
auth_type=userpass
password=pswd2         ; <-- Choisir le mot de passe
username=32

[32]
type=aor
max_contacts=1


[35]
type=endpoint
context=ramais_internos
disallow=all
allow=ulaw
allow=alaw
auth=auth35
aors=35

[auth35]
type=auth
auth_type=userpass
password=alexpswd        ; <-- mot de passe pour l'appli C alex
username=35

[35]
type=aor
max_contacts=1
