[transport-udp]
type=transport
protocol=udp
bind=0.0.0.0:5060

[endpoint-anonimo]
type=endpoint
context=recebe_chamada
disallow=all
allow=ulaw, alaw
aors=aor-anonimo

[aor-anonimo]
type=aor
max_contacts=5

[identify-anonimo]
type=identify
endpoint=endpoint-anonimo
match=0.0.0.0/0
